version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user
    
hooks:
BeforeInstall:
- location: scripts/beforecicd.sh
runas: root
AfterInstall:
- location: scripts/aftercicd.sh
runas: root
